spring:
  config:
    activate:
      on-profile: dev
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
#    datasource:
#      driver-class-name: org.h2.Driver
#      url: jdbc:h2~/test
#      username: sa
#      password:
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect
  sql:
    init:
      data-locations: classpath*:sql/init-data.sql
      mode: embedded

kakao:
  client:
    secret:
  redirect:
    uri: http://localhost:8080/kakao/callback
jwt:
  secret:
server:
  url: http://localhost:8080