server:
  port: 8080
  tomcat:
    max-http-form-post-size: 1GB

springdoc:
  swagger-ui:
    disable-swagger-default-url: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

familyRecipeBook:
  version: 1.0.0

spring:
  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB
  jpa:
    show-sql: false
management:
  endpoints:
    health:
      show-details: always
    web:
      exposure:
        include: "*"

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE